
package Q_PLAYER.Q_PLAYER_MANAGER is

    function F_EXISTS_PLAYER(V_PLAYER_NAME: T_NAME_VALUE) return BOOLEAN;
    function F_GET_PLAYER(V_PLAYER_NAME: T_NAME_VALUE) return T_PLAYER;
    function F_SAVE_PLAYER(V_PLAYER: T_PLAYER) return BOOLEAN;
    function F_CREATE_NEW_PLAYER(V_PLAYER_NAME: T_NAME_VALUE; V_PLAYER_EMAIL: T_EMAIL_VALUE) return T_PLAYER;

end Q_PLAYER.Q_PLAYER_MANAGER;