
package Q_PLAYER.Q_REPOSITORY is

    function F_EXISTS_PLAYER(V_PLAYER_NAME: T_NAME_VALUE) return BOOLEAN;
    function F_LOAD_PLAYER(V_PLAYER_NAME: T_NAME_VALUE) return T_PLAYER;
    procedure P_SAVE_PLAYER(V_PLAYER: T_PLAYER);
    procedure P_DELETE_PLAYER(V_PLAYER_NAME: T_NAME_VALUE);
    
end Q_PLAYER.Q_REPOSITORY;